// Gera os comandos de imagem dos monstros por região (famílias inteiras, ~6-7 criaturas por imagem). Uso: node tools/prompts_monstros.js praia
const fs=require('fs');const html=fs.readFileSync(__dirname+'/../combate.html','utf8');
const src=html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1]; const dj=html.match(/<script id="dexdata" type="application\/json">([\s\S]*?)<\/script>/)[1];
const E=new Function('document',src+';return {REGIONS,SPECIES,FORMS,DEXBY,POOL,MON_ART:typeof MON_ART!=="undefined"?MON_ART:null};')({getElementById:()=>({textContent:dj})});
const EN={Normal:'normal',Fogo:'fire',Água:'water',Planta:'grass',Elétrico:'electric',Inseto:'bug',Pedra:'rock',Voador:'flying',Gelo:'ice',Terra:'ground',Metálico:'steel',Psíquico:'psychic',Fantasma:'ghost',Dragão:'dragon',Fada:'fairy',Batalha:'fighting',Venenoso:'poison',Noturno:'dark'};
const ARCH={Água:['otter','round fish','sea turtle','frog','seal pup','axolotl','crab','jellyfish','seahorse','manta ray'],Voador:['songbird','owl','parrot','swallow','eagle chick'],Fogo:['fox','salamander','lion cub','phoenix chick','lizard','boar'],Planta:['sprout creature','flower bulb','mossy deer','leafy cat','cactus critter'],Inseto:['beetle','ladybug','moth','mantis','caterpillar','bee'],Pedra:['rock golem','armadillo','crystal turtle','pebble critter'],Terra:['mole','sand lizard','ground boar','badger'],Elétrico:['spark ferret','spark squirrel','storm bird','eel'],Gelo:['snow fox','penguin','ice bear cub','yeti'],Batalha:['martial monkey','boxing kangaroo','karate frog'],Venenoso:['toxic frog','snake','mushroom critter','scorpion'],Noturno:['bat','shadow fox','raven','panther cub'],Metálico:['steel beetle','robot pup','armored hedgehog'],Fantasma:['floating ghost','lantern spirit','haunted doll'],Psíquico:['mystic cat','owl sage','gem fox'],Dragão:['baby dragon','wyrm','drake'],Fada:['fairy bunny','pixie deer','star sprite'],Normal:['puppy','bunny','hamster','raccoon','cat']};
const region = process.argv[2]||'praia', POOLMODE = region==='sorteio'||region==='arena';
const R = POOLMODE ? {name: region==='arena' ? 'Loja da Arena (grau S)' : 'Cápsulas (Sorteio)'} : E.REGIONS.find(r=>r.id===region);
const HAVE = new Set(fs.readdirSync(__dirname+'/../mon').map(f=>+f.slice(0,5)));
const bases = POOLMODE ? E.POOL[region].filter(sp=>!HAVE.has(E.SPECIES[sp].dex)) : [...new Set(R.stages.flatMap(s=>s.waves.flat()).map(e=>e.replace('!','').split('@')[0]).filter(sp=>E.SPECIES[sp].dex))];
const LEGEND = region==='arena' ? ', rare and legendary-looking with elegant glowing accents and regal details' : '';
const fams = bases.map(sp=>[{id:E.SPECIES[sp].dex, nm:E.SPECIES[sp].name}, ...E.FORMS[sp].map(f=>({id:f.dex, nm:f.name}))]);
let h=0; const pick=(t,k)=>{ const a=ARCH[t]||ARCH.Normal; return a[k%a.length]; };
const batches=[]; let cur=[]; for(const f of fams){ if(cur.flat().length + f.length > 7){ batches.push(cur); cur=[]; } cur.push(f); } if(cur.length) batches.push(cur);
let out=`# Monstros da região ${R.name} (${batches.length} imagens)\n\nAnexe uma imagem já aprovada como referência de estilo em cada pedido. Mande as imagens na ordem (Lote ${region} 1, 2, 3...).\n`;
batches.forEach((b,bi)=>{ let n=0; const lines=[];
  for(const fam of b){ const e0=E.DEXBY[fam[0].id]; let first=0; h=Math.floor(fam[0].id/10)*7+bi; const arch=pick(e0.tp[0], h);
    fam.forEach((c,k)=>{ n++; if(!k) first=n; const e=E.DEXBY[c.id]; const types=e.tp.map(t=>EN[t]).join(' + ');
      lines.push(`${n}) ${c.nm.toUpperCase()} (${types} type, stage ${k+1}${k?`, evolution of #${n-1}, same species grown bigger and stronger`:''}): a cute ${arch}-like ${types} creature${LEGEND}${k?` with more elaborate ${types} features`:''}, ${['small and round','medium sized','large and majestic','huge and legendary'][Math.min(k,3)]}.`); }); }
  out += `\n## Lote ${region} ${bi+1}\n\`\`\`\nUse the same art style, rendering and lighting quality as the attached image. Creature lineup sheet for a cute monster-collecting mobile RPG: ${n} separate ORIGINAL chibi 3D cartoon monsters (not based on any existing franchise), each in a 3/4 view facing right, full body, evenly spaced in ONE row with wide gaps, evolutions look like grown versions of the previous one. Left to right:\n${lines.join('\n')}\nCrisp clean sharp edges, fully opaque. Background: solid flat pure magenta (#FF00FF), perfectly uniform. NO smoke, NO glow, NO shadows, NO text: do NOT write the names or any labels on the image (names are only for reference).\n\`\`\`\nOrdem dos nº: ${b.flat().map(c=>c.id).join(', ')}\n`; });
fs.writeFileSync(`/home/claude/Monstros_${region}.md`, out); console.log(out.slice(0,2500)); console.log('...', batches.length, 'lotes', fams.flat().length,'criaturas');
